name: code2docs
description: A library to generate samples from source code
version: 0.0.1-alpha
repository: https://github.com/angelosilvestre/code2docs

environment:
  sdk: '>=2.19.0-374.0.dev <3.0.0'

dependencies:
  collection: ^1.15.0  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
