name: code2docs
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '>=2.19.0-374.0.dev <3.0.0'

dependencies:
  collection: ^1.15.0  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
