name: code2docs
description: A library to generate samples from source code
version: 0.0.1-dev.3
repository: https://github.com/angelosilvestre/code2docs
executables:
  code2docs:
  
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  collection: ^1.15.0  
  args: ^2.3.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
