name: code2docs_cli
description: CLI for the code2docs library
version: 0.0.1-alpha
repository: https://github.com/angelosilvestre/code2docs

executables:
  code2docs:

environment:
  sdk: '>=2.19.0-467.0.dev <3.0.0'

dependencies: 
  args: ^2.3.1
  code2docs: ^0.0.1-alpha   
  path: ^1.8.3


dependency_overrides:
  code2docs:
    path: ../code2docs

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
